# Generated by Django 6.1.1 on 2026-09-29 17:05

import datetime
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatusLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankDetailsLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=60)),
                ('account_ending', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro Partner'), ('ELITE', 'Elite Master')], max_length=10)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PAID', 'Paid')], default='PAID', max_length=10)),
                ('bank_label', models.CharField(blank=True, max_length=80)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanChangeLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_tier', models.CharField(blank=True, max_length=10)),
                ('new_tier', models.CharField(max_length=10)),
                ('old_cycle', models.CharField(blank=True, max_length=10)),
                ('new_cycle', models.CharField(max_length=10)),
                ('old_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='portfolio/')),
                ('blueprint', models.FileField(blank=True, upload_to='portfolio/blueprints/')),
                ('technical_specs', models.FileField(blank=True, upload_to='portfolio/specs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('STATUS', 'Status changed'), ('RESCHEDULE', 'Rescheduled'), ('FEEDBACK', 'Feedback recorded'), ('REASSIGN', 'Reassigned'), ('AMOUNT', 'Amount set')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=120)),
                ('new_value', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('provider_reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('removed_reason', models.CharField(blank=True, max_length=255)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_availability', models.BooleanField(default=True)),
                ('range_start', models.DateField(blank=True, null=True)),
                ('range_end', models.DateField(blank=True, null=True)),
                ('services_offered', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('REPAIRS', 'Repairs'), ('MAINTENANCE', 'Maintenance'), ('INSPECTION', 'Inspection'), ('INSTALLATION', 'Installation'), ('OTHER', 'Other')], max_length=20), blank=True, default=list)),
                ('day_start', models.TimeField(default=datetime.time(9, 0))),
                ('day_end', models.TimeField(default=datetime.time(18, 0))),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('group', models.CharField(choices=[('TECHNICAL', 'Technical Services'), ('CREATIVE', 'Creative & Personal Services')], default='TECHNICAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('profession_title', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MORE_INFO', 'More Information Needed')], default='PENDING', max_length=20)),
                ('verification_stage', models.CharField(choices=[('BACKGROUND', 'Background Check'), ('IDENTITY', 'Identity Verification'), ('LICENSE', 'License Verification'), ('INSURANCE', 'Insurance Check')], default='BACKGROUND', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', max_length=20)),
                ('average_rating', models.FloatField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('completed_jobs_count', models.PositiveIntegerField(default=0)),
                ('cover_photo', models.ImageField(blank=True, upload_to='providers/')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('district', models.CharField(blank=True, choices=[('PORT_LOUIS', 'Port Louis'), ('PAMPLEMOUSSES', 'Pamplemousses'), ('RIVIERE_DU_REMPART', 'Rivière du Rempart'), ('FLACQ', 'Flacq'), ('GRAND_PORT', 'Grand Port'), ('SAVANNE', 'Savanne'), ('PLAINES_WILHEMS', 'Plaines Wilhems'), ('MOKA', 'Moka'), ('BLACK_RIVER', 'Black River'), ('ISLAND_WIDE', 'Island Wide')], max_length=30)),
                ('town', models.CharField(blank=True, max_length=80)),
                ('areas_served', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list)),
                ('client_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('BOTH', 'Residential & Commercial')], default='BOTH', max_length=20)),
                ('project_scale', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', max_length=10)),
                ('main_specializations', models.TextField(blank=True)),
                ('specialty_areas', models.TextField(blank=True)),
                ('common_issues', models.TextField(blank=True)),
                ('service_requirements', models.TextField(blank=True)),
                ('process_notes', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=60)),
                ('bank_account_number', models.CharField(blank=True, max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('job_type', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('REPAIRS', 'Repairs'), ('MAINTENANCE', 'Maintenance'), ('INSPECTION', 'Inspection'), ('INSTALLATION', 'Installation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('preferred_date', models.DateField()),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACCEPTED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('admin_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestPhoto',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requests/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro Partner'), ('ELITE', 'Elite Master')], default='STARTER', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10)),
                ('search_rank', models.PositiveSmallIntegerField(default=1)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('BRN', 'Business Registration Document'), ('NATIONAL_ID', 'National ID'), ('LICENSE', 'License'), ('CERTIFICATION', 'Certification'), ('INSURANCE', 'Insurance')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to='documents/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STAGE', 'Stage changed'), ('NOTE', 'Note added'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=10)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
